### ISSUE TITLE
How to increase 'grpc.max_send_message_length' and 'grpc.max_receive_message_length'?

### ISSUE THREAD

**Issue by bendangnuksung** [Abhijit-2592/model-server#4]
Thanks for this repo, I was able to easily implement it. 

Coming to the issue, I am getting this error `"Received message larger than max (9216051 vs. 4194304)","grpc_status":8}"` whenever I am sending a bigger image. Is there a way to increase the `grpc.max_send_message_length` and `grpc.max_receive_message_length` ?

**Comment by Abhijit-2592** [comment]
Hi @bendangnuksung thanks for checking out my project. The code to configure the size of message is not updated to the pip repository. Use the **method 2** mentioned in **readme** to install and you should see the option to set limit for message size via the `command line`

**Comment by bendangnuksung** [comment]
@Abhijit-2592 Thank you for the response. I have tried **Method 2** as you suggested, it did install the package but it didn't show any option to set the message size. I press `ctrl+c` when it prompted for UserId and password as mentioned in the README. 

I also encountered some small problems when trying to install using method 2 which I was able to solve installing some pre-requirements packages: `grpcio-tools`, `twine`, `protobuf-compiler`

**Comment by Abhijit-2592** [comment]
@bendangnuksung. Just checking did you install from the newly created wheel (from method 2) and uninstalled the pip version? try `python -m model_server.runserver --help` from the command line. It will show command line arguments to change what you require.

**Comment by bendangnuksung** [comment]
Thanks @Abhijit-2592 I totally misunderstood when you said 
> Use the method 2 mentioned in readme to install and you should see the option to set limit for message size 

I thought I need to set the limit during the installation.
Once again thanks for the help and great repo 👍 

One more question which is out from the topic. Does the **model_server** supports **stream-unary** or **stream-stream**  data transmission?

**Comment by bendangnuksung** [comment]
Finally solved it, what I needed was to increase the `max_receive_message_length` in client code.
```python
...
options = [('grpc.max_receive_message_length', 100 * 1024 * 1024)]
channel = grpc.insecure_channel('localhost:5001', options=options)  
...
```
